---
services:
  main:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.12
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
  selenium:
    image: selenium/standalone-chrome:119.0
    ports:
      - 7900:7900
    shm_size: 2g
